logging:
  level:
    root: warn
  file: logs/log.log

spring:
  aop:
    auto: true
    proxy-target-class: true
dht:
  bootstrap-nodes:
    - router.bittorrent.com:6881
    - dht.transmissionbt.com:6881
    - router.utorrent.com:6881
    - dht.aelitis.com:6881
    - localhost:8888
  ip-for-bep0042: 223.155.69.210
  join-dht-interval: 3000
  join-dht-count: 30000
  join-dht-max-size: 100000